CREATE TABLE "Client" (
                          "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                          "Name" text NULL,
                          "Email" text NULL,
                          "MobilePhone" text NULL,
                          "Telegram" text NULL,
                          "Coordinate" text NULL,
                          CONSTRAINT "PK_Client" PRIMARY KEY ("Id")
);


CREATE TABLE "RightInfo" (
                             "Right" integer NOT NULL,
                             "Description" text NULL,
                             CONSTRAINT "PK_RightInfo" PRIMARY KEY ("Right")
);


CREATE TABLE "User" (
                        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                        "Name" text NULL,
                        "Email" text NULL,
                        "Picture" text NULL,
                        "MobilePhone" text NULL,
                        "Telegram" text NULL,
                        "Coordinate" text NULL,
                        CONSTRAINT "PK_User" PRIMARY KEY ("Id")
);


CREATE TABLE "Meeting" (
                           "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                           "ClientId" integer NOT NULL,
                           "AvailableTimeStart" timestamp without time zone NOT NULL,
                           "AvailableTimeEnd" timestamp without time zone NOT NULL,
                           "StartTime" timestamp without time zone NOT NULL,
                           "EndTime" timestamp without time zone NOT NULL,
                           "Coordinate" text NULL,
                           CONSTRAINT "PK_Meeting" PRIMARY KEY ("Id"),
                           CONSTRAINT "FK_Meeting_Client_ClientId" FOREIGN KEY ("ClientId") REFERENCES "Client" ("Id") ON DELETE CASCADE
);


CREATE TABLE "ManagerSchedule" (
                                   "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                   "UserId" integer NOT NULL,
                                   "StartTime" timestamp without time zone NOT NULL,
                                   "EndTime" timestamp without time zone NOT NULL,
                                   "StartCoordinate" text NULL,
                                   "EndCoordinate" text NULL,
                                   CONSTRAINT "PK_ManagerSchedule" PRIMARY KEY ("Id"),
                                   CONSTRAINT "FK_ManagerSchedule_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE CASCADE
);


CREATE TABLE "UserRight" (
                             "UserId" integer NOT NULL,
                             "Right" integer NOT NULL,
                             CONSTRAINT "PK_UserRight" PRIMARY KEY ("UserId", "Right"),
                             CONSTRAINT "FK_UserRight_RightInfo_Right" FOREIGN KEY ("Right") REFERENCES "RightInfo" ("Right") ON DELETE CASCADE,
                             CONSTRAINT "FK_UserRight_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Route" (
                          "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                          "ManagerScheduleId" integer NOT NULL,
                          "SuitableMeetings" text NULL,
                          "Distance" double precision NOT NULL,
                          "WaitingTime" double precision NOT NULL,
                          "FinishesAsPreferred" boolean NOT NULL,
                          CONSTRAINT "PK_Route" PRIMARY KEY ("Id"),
                          CONSTRAINT "FK_Route_ManagerSchedule_ManagerScheduleId" FOREIGN KEY ("ManagerScheduleId") REFERENCES "ManagerSchedule" ("Id") ON DELETE CASCADE
);


CREATE INDEX "IX_ManagerSchedule_UserId" ON "ManagerSchedule" ("UserId");


CREATE INDEX "IX_Meeting_ClientId" ON "Meeting" ("ClientId");


CREATE INDEX "IX_Route_ManagerScheduleId" ON "Route" ("ManagerScheduleId");


CREATE UNIQUE INDEX "IX_User_Email" ON "User" ("Email");


CREATE INDEX "IX_UserRight_Right" ON "UserRight" ("Right");

